# Generated by Django 4.2.6 on 2024-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_writearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WriteArticle',
        ),
    ]
