# Generated by Django 4.2.6 on 2024-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_newsarticle_status_delete_writearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
