# Generated by Django 4.2.6 on 2024-11-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_newsarticle_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
